name: "Waveshare PWM Fan HAT"
description: "PWM fan and display support for the Waveshare PWM fan HAT."
version: "0.2.0"
slug: "pwm_fan_hat"
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-10
  - /dev/i2c-11
options:
  fan_min_temp: 25
  fan_max_temp: 80
  delta_temp: 5
  update_interval: 2
  rotate_oled: false
  display_mode: fan_status
schema:
  fan_min_temp: int
  fan_max_temp: int
  delta_temp: int
  update_interval: int
  rotate_oled: bool
  display_mode: list(fan_status|ip_address)
